export const SEQUELIZE = 'SEQUELIZE';
export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY';
export const DELETE_MESSAGE = "Item com id '?id' removido com sucesso";
export const GET_NOT_FOUND_MESSAGE = "Item com id '?id' não encontrado";
export const SEQUELIZE_FK_ERROR_MESSAGE = "SequelizeForeignKeyConstraintError";
export const SEQUELIZE_VALIDATION_ERROR_MESSAGE = "SequelizeValidationError";
export const SEQUELIZE_DB_ERROR_MESSAGE = "SequelizeDatabaseError";
export const DELETE_FK_ERROR_MESSAGE = "Item com id '?id' possui referência(s) em outra(s) tabela(s). Não foi possível remover";
export const POST_VALIDATION_ERROR_MESSAGE = "Item com campos/valores incorretos ou faltantes. Não foi possível criar";